spring:
  application:
    name: travel-planner
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/travel_planner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update # doi thanh "validate" va dung Flyway/Liquibase khi len production that
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

gemini:
  api:
    key: "YOUR_GEMINI_API_KEY_HERE"
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"

ors:
  api:
    key: "YOUR_ORS_API_KEY_HERE"
    url: "https://api.openrouteservice.org"

openweathermap:
  api:
    key: "YOUR_OWM_API_KEY_HERE"
    url: "https://api.openweathermap.org/data/2.5/forecast"

rate-limit:
  requests-per-minute: 5
