spring:
  application:
    name: travel-planner
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/travel_planner}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history
  sql:
    init:
      mode: never
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

ors:
  api:
    url: "https://api.openrouteservice.org"
    key: ${ORS_API_KEY:}

openweathermap:
  api:
    url: "https://api.openweathermap.org/data/2.5/forecast"
    key: ${OPENWEATHERMAP_API_KEY:}

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
    key: ${GEMINI_API_KEY:}

rate-limit:
  requests-per-minute: 5

app:
  admin:
    email: ${APP_ADMIN_EMAIL:admin@localhost}
    password: ${APP_ADMIN_PASSWORD:admin}
